#ifndef MACHINE_COMMON_GLOBAL_H
#define MACHINE_COMMON_GLOBAL_H

#include <QtGlobal>

#if defined(MACHINE_COMMON_PROJECT)
# define MACHINE_COMMON_EXPORT Q_DECL_EXPORT
#else
# define MACHINE_COMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // MACHINE_COMMON_GLOBAL_H
